package com;

public class ProjectileID {
	//TODO this doesn't need to be its own file

	public static String[] projectiles = {
		"00 capsule",
		"01 box",
		"02 barrel",
		"03 egg",
		"04 partyball",
		"05 cannon",
		"06 bombomb",
		"07 mr. saturn",
		"08 heart",
		"09 tomato",
		"0A star",
		"0B bat",
		"0C sword",
		"0D umbrella",
		"0E green shell",
		"0F red shell",
		"10 gun",
		"11 freezie",
		"12 food",
		"13 mine",
		"14 bumper",
		"15 super scope",
		"16 star rod",
		"17 lip stick",
		"18 fan",
		"19 fire flower",
		"1A big mushroom",
		"1B small mushroom",
		"1C hammer",
		"1D warp star",
		"1E screw attack",
		"1F rabbit hood",
		"20 metal",
		"21 cloak",
		"22 pokeball",
		"23",
		"24",
		"25",
		"26",
		"27",
		"28",
		"29",
		"2A",
		"2B goomba",
		"2C redead",
		"2D octarok",
		"2E otosea",
		"2F Stone",
		"30 Mario's fire",
		"31 Dr.Mario's Capsule",
		"32 Kirby's Cutter beam",
		"33 Kirby's Hammer",
		"34 Raygun beam",
		"35",
		"36 Fox's laser",
		"37 ? Falco's Laser ?",
		"38 Fox's shadow",
		"39 Falco's shadow",
		"3A Link's bomb",
		"3B Young Link's bomb",
		"3C Link's boomerang",
		"3D Young Link's boomerang",
		"3E Link's Hookshot",
		"3F Young Link's Hookshot",
		"40 Arrow",
		"41 Fire Arrow",
		"42 PK Fire",
		"43 PK Flash",
		"44 PK Flash",
		"45 PK Thunder",
		"46 PK Thunder",
		"47 PK Thunder",
		"48 PK Thunder",
		"49 PK Thunder",
		"4A Fox's Blaster",
		"4B Falco's Blaster",
		"4C ? Link's Arrow ?",
		"4D Young Link's arrow",
		"4E PK Flash (explosion)",
		"4F Needle(thrown)",
		"50 Needle",
		"51 Pikachu's Thunder",
		"52 Pichu's Thunder",
		"53 Mario's cape",
		"54 Dr.Mario's cape",
		"55 Smoke (Sheik)",
		"56 Yoshi's egg(thrown)",
		"57",
		"58 Yoshi's Star",
		"59 Pikachu's thunder",
		"5A Pikachu's thunder",
		"5B Pichu's thunder",
		"5C Pichu's thunder",
		"5D Samus's bomb",
		"5E Samus's chargeshot",
		"5F Missile",
		"60 Grapple beam",
		"61 Sheik's chain",
		"62",
		"63 Turnip",
		"64 Bowser's flame",
		"65 Ness's bat",
		"66 Yoyo",
		"67 Peach's parasol",
		"68 Toad",
		"69 Luigi's fire",
		"6A Ice(Iceclimbers)",
		"6B Blizzard",
		"6C Zelda's fire",
		"6D Zelda's fire (explosion)",
		"6E",
		"6F Toad's spore",
		"70 Mewtwo's Shadowball",
		"71 Iceclimbers' Up-B",
		"72 Pesticide",
		"73 Manhole",
		"74 Fire(G&W)",
		"75 Parashute",
		"76 Turtle",
		"77 Sperky",
		"78 Judge",
		"79",
		"7A Sausage",
		"7B Milk (Young Link)",
		"7C Firefighter(G&W)",
		"7D Masterhand's laser",
		"7E Masterhand's bullet",
		"7F",
		"80",
		"81 Crazyhand's Bomb",
		"82",
		"83",
		"84",
		"85",
		"86",
		"87",
		"88",
		"89",
		"8A",
		"8B",
		"8C",
		"8D",
		"8E",
		"8F",
		"90",
		"91",
		"92",
		"93",
		"94",
		"95",
		"96",
		"97  (crashes with peach pulls out)",
		"98",
		"99",
		"9A",
		"9B",
		"9C",
		"9D",
		"9E Coin",
		"9F",
		"A0 Null pokemon entry?",
		"A1 Goldeen (Tosakinto)",
		"A2 Chicorita",
		"A3 Snorlax",
		"A4 Blastoise",
		"A5 Weezing (Matadogas)",
		"A6 Charizard (Lizardon)",
		"A7 Moltres",
		"A8 Zapdos",
		"A9 Articuno",
		"AA Wobbuffet",
		"AB Scizor",
		"AC Unown",
		"AD Entei",
		"AE Raikou",
		"AF Suicune",
		"B0 Bellossom (Kireihana)",
		"B1 Electrode (Marumine)",
		"B2 Lugia",
		"B3 Ho-oh",
		"B4 Metamon",
		"B5 Clefairy",
		"B6 Togepi",
		"B7 Mew",
		"B8 Celebi",
		"B9 Staryu (Hitodeman)",
		"BA Chansey",
		"BB Porygon2",
		"BC Cyndaquil (Hinoarashi)",
		"BD Marill",
		"BE Venusaur (Fushigibana)",
		"BF Chikorita's Leaf",
		"C0 Blastoise's Water",
		"C1 Weezing's Gas",
		"C2 Weezing's Gas",
		"C3 Burn ??? Fire something",
		"C4 Burn ??? Fire something",
		"C5 Charizard's Breath",
		"C6 Charizard's Breath",
		"C7 Unowns",
		"C8 Lugia's Aeroblast",
		"C9 Lugia's Aeroblast",
		"CA Lugia's Aeroblast",
		"CB Ho-oh's Flame",
		"CC Staryu's Star",
		"CD Healing Egg",
		"CE Cyndaquil's Fire",
		"CF ??? invisible",
		"D0",
		"D1 Target",
		"D2 Shyguy (Heiho)",
		"D3 Koopa(Green) (Nokonoko)",
		"D4 Koopa(Red) (PataPata)",
		"D5 Likelile",
		"D6 (old-lead)",
		"D7 (old-octa)",
		"D8 (old-otto)",
		"D9 White Bear (whitebea)",
		"DA klap",
		"DB Paratroopa (Green) (zgshell)",
		"DC Paratroopa (Red) (zrshell)",
		"DD",
		"DE",
		"DF",
		"E0 (crashes when peach pulls out)",
		"E1 Apple",
		"E2",
		"E3",
		"E4",
		"E5",
		"E6 Tool",
		"E7",
		"E8",
		"EA Arwing Laser",
		"EB Wolfen Laser",
		"EC",
		"ED",
		"EE",
		"EF",
		"F0",
		"F1",
		"F2",
		"F3",
		"F4",
		"F5",
		"F6",
		"F7",
		"F8",
		"F9 (crashes when peach pulls out)",
		"FA",
		"FB",
		"FC",
		"FD",
		"FE",
		"FF",
	
	};
}
