package com;

public class SubAction {
	public static SubAction[] subActions = {
		new SubAction(0x2e, "Jab 1"),	
		new SubAction(0x2f, "Jab 2"),
		new SubAction(0x30, "Jab 3?"),	
		new SubAction(0x31, "Rapid Jab Start"),	
		new SubAction(0x32, "Rapid Jab Loop"),	
		new SubAction(0x33, "Rapid Jab End"),	
		new SubAction(0x34, "Dash Attack"),	
		new SubAction(0x35, "Forward-Tilt (High)"),	
		new SubAction(0x36, "Forward-Tilt (Mid-High)"),		
		new SubAction(0x37, "Forward-Tilt (Middle)"),	
		new SubAction(0x38, "Forward-Tilt (Mid-Low)"),		
		new SubAction(0x39, "Forward-Tilt (Low)"),		
		new SubAction(0x3a, "Up-Tilt"),		
		new SubAction(0x3b, "Down-Tilt"),		
		new SubAction(0x3c, "Forward-Smash (High)"),	
		new SubAction(0x3d, "Forward-Smash (Mid-High)"),		
		new SubAction(0x3e, "Forward-Smash (Middle)"),
		new SubAction(0x3f, "Forward-Smash (Mid-Low)"),		
		new SubAction(0x40, "Forward-Smash (Low)"),	
		//new SubAction(0x41, "Smash Attack Charge?"),	
		new SubAction(0x42, "Up-Smash"),		
		new SubAction(0x43, "Down-Smash"),		
		new SubAction(0x44, "Neutral-Air"),		
		new SubAction(0x45, "Forward-Air"),		
		new SubAction(0x46, "Back-Air"),	
		new SubAction(0x47, "Up-Air"),		
		new SubAction(0x48, "Down-Air"),
		new SubAction(0xf7,"Forward Throw"),
		new SubAction(0xf8,"Back Throw"),
		new SubAction(0xf9,"Up Throw"),
		new SubAction(0xfa,"Down Throw"),
	};
	
	public static SubAction[] subActionsAll = {

		new SubAction(0x2,"b'Wait1"),	
		new SubAction(0x3,"b'Wait2"),		
		new SubAction(0x4,"b'Wait3"),	
		new SubAction(0x5,"b'Wait4"),	
		new SubAction(0x6,"b'WaitItem"),	
		new SubAction(0x7,"b'WalkSlow"),	
		new SubAction(0x8,"b'WalkMiddle"),	
		new SubAction(0x9,"b'WalkFast"),	
		new SubAction(0xa,"b'Turn"),	
		new SubAction(0xb,"b'TurnRun"),	
		new SubAction(0xc,"b'Dash"),	
		new SubAction(0xd,"b'Run"),	
		new SubAction(0xe,"b'RunBrake"),	
		new SubAction(0xf,"b'KneeBend"),	
		new SubAction(0x10,"b'JumpF"),	
		new SubAction(0x11,"b'JumpB"),	
		new SubAction(0x12,"b'JumpAerialF"),		
		new SubAction(0x13,"b'JumpAerialB"),		
		new SubAction(0x14,"b'Fall"),
		new SubAction(0x15,"b'FallF"),
		new SubAction(0x16,"b'FallB"),
		new SubAction(0x17,"b'FallAerial"),	
		new SubAction(0x18,"b'FallAerialF"),	
		new SubAction(0x19,"b'FallAerialB"),	
		new SubAction(0x1a,"b'FallSpecial"),	
		new SubAction(0x1b,"b'FallSpecialF"),	
		new SubAction(0x1c,"b'FallSpecialB"),	
		new SubAction(0x1d,"b'DamageFall"),	
		new SubAction(0x1e,"b'Squat"),
		new SubAction(0x1f,"b'SquatWait1"),	
		new SubAction(0x20,"b'SquatWait2"),	
		new SubAction(0x21,"b'SquatWaitItem"),	
		new SubAction(0x22,"b'SquatR"),
		new SubAction(0x23,"b'Landing"),
		new SubAction(0x24,"b'LandingFallSpecial"),		
		new SubAction(0x25,"b'GuardOn"),
		new SubAction(0x26,"b'Guard"),
		new SubAction(0x27,"b'GuardOff"),
		new SubAction(0x28,"b'GuardDamage"),	
		new SubAction(0x29,"b'EscapeN"),
		new SubAction(0x2a,"b'EscapeF"),
		new SubAction(0x2b,"b'EscapeB"),
		new SubAction(0x2c,"b'EscapeAir"),
		new SubAction(0x2d,"b'Rebound"),
		new SubAction(0x2e,"b'Attack11"),
		new SubAction(0x2f,"b'Attack12"),
		new SubAction(0x30,"b'Attack13"),
		new SubAction(0x31,"b'Attack100Start"),	
		new SubAction(0x32,"b'Attack100Loop"),	
		new SubAction(0x33,"b'Attack100End"),	
		new SubAction(0x34,"b'AttackDash"),	
		new SubAction(0x35,"b'AttackS3Hi"),	
		new SubAction(0x36,"b'AttackS3HiS"),	
		new SubAction(0x37,"b'AttackS3S"),
		new SubAction(0x38,"b'AttackS3LwS"),	
		new SubAction(0x39,"b'AttackS3Lw"),	
		new SubAction(0x3a,"b'AttackHi3"),
		new SubAction(0x3b,"b'AttackLw3"),
		new SubAction(0x3c,"b'AttackS4Hi"),	
		new SubAction(0x3d,"b'AttackS4HiS"),	
		new SubAction(0x3e,"b'AttackS4S"),
		new SubAction(0x3f,"b'AttackS4LwS"),	
		new SubAction(0x40,"b'AttackS4Lw"),	
		new SubAction(0x41,"b'AttackS4Hold"),	
		new SubAction(0x42,"b'AttackHi4"),
		new SubAction(0x43,"b'AttackLw4"),
		new SubAction(0x44,"b'AttackAirN"),	
		new SubAction(0x45,"b'AttackAirF"),	
		new SubAction(0x46,"b'AttackAirB"),	
		new SubAction(0x47,"b'AttackAirHi"),	
		new SubAction(0x48,"b'AttackAirLw"),	
		new SubAction(0x49,"b'LandingAirN"),	
		new SubAction(0x4a,"b'LandingAirF"),	
		new SubAction(0x4b,"b'LandingAirB"),	
		new SubAction(0x4c,"b'LandingAirHi"),	
		new SubAction(0x4d,"b'LandingAirLw"),	
		new SubAction(0x4e,"b'LightGet"),
		new SubAction(0x4f,"b'LightThrowF"),	
		new SubAction(0x50,"b'LightThrowB"),	
		new SubAction(0x51,"b'LightThrowHi"),	
		new SubAction(0x52,"b'LightThrowLw"),	
		new SubAction(0x53,"b'LightThrowDash"),	
		new SubAction(0x54,"b'LightThrowDrop"),	
		new SubAction(0x55,"b'LightThrowAirF"),	
		new SubAction(0x56,"b'LightThrowAirB"),	
		new SubAction(0x57,"b'LightThrowAirHi"),	
		new SubAction(0x58,"b'LightThrowAirLw"),	
		new SubAction(0x59,"b'HeavyGet"),
		new SubAction(0x5a,"b'HeavyWalk1"),	
		new SubAction(0x5b,"b'HeavyWalk2"),	
		new SubAction(0x5c,"b'HeavyThrowF"),	
		new SubAction(0x5d,"b'HeavyThrowB"),	
		new SubAction(0x5e,"b'HeavyThrowHi"),	
		new SubAction(0x5f,"b'HeavyThrowLw"),	
		new SubAction(0x60,"b'LightThrowF4"),	
		new SubAction(0x61,"b'LightThrowB4"),	
		new SubAction(0x62,"b'LightThrowHi4"),	
		new SubAction(0x63,"b'LightThrowLw4"),	
		new SubAction(0x64,"b'LightThrowAirF4"),	
		new SubAction(0x65,"b'LightThrowAirB4"),	
		new SubAction(0x66,"b'LightThrowAirHi4"),	
		new SubAction(0x67,"b'LightThrowAirLw4"),	
		new SubAction(0x68,"b'HeavyThrowF4"),	
		new SubAction(0x69,"b'HeavyThrowB4"),	
		new SubAction(0x6a,"'HeavyThrowHi4"),	
		new SubAction(0x6b,"b'HeavyThrowLw4"),	
		new SubAction(0x6c,"b'SwordSwing1"),	
		new SubAction(0x6d,"b'SwordSwing3"),	
		new SubAction(0x6e,"b'SwordSwing4"),	
		new SubAction(0x6f,"b'SwordSwingDash"),	
		new SubAction(0x70,"b'BatSwing1"),
		new SubAction(0x71,"b'BatSwing3"),
		new SubAction(0x72,"b'BatSwing4"),
		new SubAction(0x73,"b'BatSwingDash"),	
		new SubAction(0x74,"b'ParasolSwing1"),	
		new SubAction(0x75,"b'ParasolSwing3"),	
		new SubAction(0x76,"b'ParasolSwing4"),	
		new SubAction(0x77,"b'ParasolSwingDash"),	
		new SubAction(0x78,"b'HarisenSwing1"),	
		new SubAction(0x79,"b'HarisenSwing3"),	
		new SubAction(0x7a,"b'HarisenSwing4"),	
		new SubAction(0x7b,"b'HarisenSwingDash"),	
		new SubAction(0x7c,"b'StarRodSwing1"),	
		new SubAction(0x7d,"b'StarRodSwing3"),	
		new SubAction(0x7e,"b'StarRodSwing4"),	
		new SubAction(0x7f,"b'StarRodSwingDash"),	
		new SubAction(0x80,"b'LipStickSwing1"),	
		new SubAction(0x81,"b'LipStickSwing3"),	
		new SubAction(0x82,"b'LipStickSwing4"),	
		new SubAction(0x83,"b'LipStickSwingDash"),	
		new SubAction(0x84,"b'ItemHammerWait"),	
		new SubAction(0x85,"b'ItemHammerMove"),	
		new SubAction(0x86,"b'ItemParasolOpen"),	
		new SubAction(0x87,"b'ItemParasolFall"),	
		new SubAction(0x88,"b'ItemParasolFallSpecial"),		
		new SubAction(0x89,"b'ItemParasolDamageFall"),	
		new SubAction(0x8a,"b'LGunShoot"),
		new SubAction(0x8b,"b'LGunShootAir"),	
		new SubAction(0x8c,"b'LGunShootEmpty"),	
		new SubAction(0x8d,"b'LGunShootAirEmpty"),	
		new SubAction(0x8e,"b'FireFlowerShoot"),	
		new SubAction(0x8f,"b'FireFlowerShootAir"),		
		new SubAction(0x90,"b'ItemScrew"),
		new SubAction(0x91,"b'ItemScrewAir"),	
		new SubAction(0x92,"b'DamageScrew"),	
		new SubAction(0x93,"b'DamageScrewAir"),	
		new SubAction(0x94,"b'ItemBlind"),
		new SubAction(0x95,"b'ItemScopeStart"),	
		new SubAction(0x96,"b'ItemScopeRapid"),	
		new SubAction(0x97,"b'ItemScopeFire"),	
		new SubAction(0x98,"b'ItemScopeEnd"),	
		new SubAction(0x99,"b'ItemScopeAirStart"),	
		new SubAction(0x9a,"b'ItemScopeAirRapid"),	
		new SubAction(0x9b,"b'ItemScopeAirFire"),	
		new SubAction(0x9c,"b'ItemScopeAirEnd"),	
		new SubAction(0x9d,"b'ItemScopeStartEmpty"),		
		new SubAction(0x9e,"b'ItemScopeRapidEmpty"),		
		new SubAction(0x9f,"b'ItemScopeFireEmpty"),	
		new SubAction(0xa0,"b'ItemScopeEndEmpty"),
		new SubAction(0xa1,"b'ItemScopeAirStartEmpty"),	
		new SubAction(0xa2,"b'ItemScopeAirRapidEmpty"),	
		new SubAction(0xa3,"b'ItemScopeAirFireEmpty"),	
		new SubAction(0xa4,"b'ItemScopeAirEndEmpty"),	
		new SubAction(0xa5,"b'DamageHi1"),
		new SubAction(0xa6,"b'DamageHi2"),
		new SubAction(0xa7,"b'DamageHi3"),
		new SubAction(0xa8,"b'DamageN1"),
		new SubAction(0xa9,"b'DamageN2"),
		new SubAction(0xaa,"b'DamageN3"),
		new SubAction(0xab,"b'DamageLw1"),
		new SubAction(0xac,"b'DamageLw2"),
		new SubAction(0xad,"b'DamageLw3"),
		new SubAction(0xae,"b'DamageAir1"),	
		new SubAction(0xaf,"b'DamageAir2"),	
		new SubAction(0xb0,"b'DamageAir3"),	
		new SubAction(0xb1,"b'DamageFlyHi"),	
		new SubAction(0xb2,"b'DamageFlyN"),	
		new SubAction(0xb3,"b'DamageFlyLw"),	
		new SubAction(0xb4,"b'DamageFlyTop"),	
		new SubAction(0xb5,"b'DamageFlyRoll"),	
		new SubAction(0xb6,"b'DamageElec"),	
		new SubAction(0xb7,"b'DownBoundU"),	
		new SubAction(0xb8,"b'DownWaitU	"),
		new SubAction(0xb9,"b'DownDamageU"),	
		new SubAction(0xba,"b'DownStandU"),	
		new SubAction(0xbb,"b'DownAttackU"),	
		new SubAction(0xbc,"b'DownFowardU"),	
		new SubAction(0xbd,"b'DownBackU"),
		new SubAction(0xbe,"b'DownSpotU	"),
		new SubAction(0xbf,"b'DownBoundD"),	
		new SubAction(0xc0,"b'DownWaitD"),
		new SubAction(0xc1,"b'DownDamageD"),	
		new SubAction(0xc2,"b'DownStandD"),	
		new SubAction(0xc3,"b'DownAttackD"),	
		new SubAction(0xc4,"b'DownFowardD"),	
		new SubAction(0xc5,"b'DownBackD"),
		new SubAction(0xc6,"b'DownSpotD"),
		new SubAction(0xc7,"b'Passive"),
		new SubAction(0xc8,"b'PassiveStandF"),	
		new SubAction(0xc9,"b'PassiveStandB"),	
		new SubAction(0xca,"b'PassiveWall"),	
		new SubAction(0xcb,"b'PassiveWallJump"),	
		new SubAction(0xcc,"b'PassiveCeil"),	
		new SubAction(0xcd,"b'FuraFura"),
		new SubAction(0xce,"b'FuraSleepStart"),	
		new SubAction(0xcf,"b'FuraSleepLoop"),	
		new SubAction(0xd0,"b'FuraSleepEnd"),	
		new SubAction(0xd1,"b'Pass"),
		new SubAction(0xd2,"b'Ottotto"),
		new SubAction(0xd3,"b'OttottoWait"),	
		new SubAction(0xd4,"b'WallDamage"),	
		new SubAction(0xd5,"b'StopWall"),
		new SubAction(0xd6,"b'StopCeil"),
		new SubAction(0xd7,"b'MissFoot"),
		new SubAction(0xd8,"b'CliffCatch"),	
		new SubAction(0xd9,"b'CliffWait1"),	
		new SubAction(0xda,"b'CliffWait2"),	
		new SubAction(0xdb,"b'CliffClimbSlow"),	
		new SubAction(0xdc,"b'CliffClimbQuick"),	
		new SubAction(0xdd,"b'CliffAttackSlow"),	
		new SubAction(0xde,"b'CliffAttackQuick"),	
		new SubAction(0xdf,"b'CliffEscapeSlow"),	
		new SubAction(0xe0,"b'CliffEscapeQuick"),	
		new SubAction(0xe1,"b'CliffJumpSlow1"),	
		new SubAction(0xe2,"b'CliffJumpSlow2"),	
		new SubAction(0xe3,"b'CliffJumpQuick1"),	
		new SubAction(0xe4,"b'CliffJumpQuick2"),	
		new SubAction(0xe5,"b'SlipDown"),
		new SubAction(0xe6,"b'Slip"),
		new SubAction(0xe7,"b'SlipTurn"),
		new SubAction(0xe8,"b'SlipDash"),
		new SubAction(0xe9,"b'SlipWait"),
		new SubAction(0xea,"b'SlipStand"),
		new SubAction(0xeb,"b'SlipAttack"),	
		new SubAction(0xec,"b'SlipEscapeF"),	
		new SubAction(0xed,"b'SlipEscapeB"),	
		new SubAction(0xee,"b'Entry"),
		new SubAction(0xef,"b'AppealR"),
		new SubAction(0xf0,"b'AppealL"),
		new SubAction(0xf1,"b'AppealS"),
		new SubAction(0xf2,"b'Catch"),
		new SubAction(0xf3,"b'CatchDash"),
		new SubAction(0xf4,"b'CatchWait"),
		new SubAction(0xf5,"b'CatchAttack"),	
		new SubAction(0xf6,"b'CatchCut"),
		new SubAction(0xf7,"b'ThrowF"),
		new SubAction(0xf8,"b'ThrowB"),
		new SubAction(0xf9,"b'ThrowHi"),
		new SubAction(0xfa,"b'ThrowLw"),
		new SubAction(0xfb,"b'CapturePulledHi"),	
		new SubAction(0xfc,"b'CaptureWaitHi"),
		new SubAction(0xfd,"b'CaptureDamageHi"),	
		new SubAction(0xfe,"b'CapturePulledLw"),	
		new SubAction(0xff,"b'CaptureWaitLw"),	
		new SubAction(0x100,"b'CaptureDamageLw"),	
		new SubAction(0x101,"b'CaptureCut"),	
		new SubAction(0x102,"b'CaptureJump"),	
		new SubAction(0x103,"b'CaptureNeck"),	
		new SubAction(0x104,"b'CaptureFoot"),	
		new SubAction(0x105,"b'Zitabata	"),
		new SubAction(0x106,"b'ThrownF"),
		new SubAction(0x107,"b'ThrownB"),
		new SubAction(0x108,"b'ThrownHi"),
		new SubAction(0x109,"b'ThrownLw"),
		new SubAction(0x10a,"b'ThrownLwWomen"),	
		new SubAction(0x10b,"b'ShoulderedWait"),	
		new SubAction(0x10c,"b'ShoulderedWalkSlow"),		
		new SubAction(0x10d,"b'ShoulderedWalkMiddle"),		
		new SubAction(0x10e,"b'ShoulderedWalkFast"),	
		new SubAction(0x10f,"b'ShoulderedTurn"),
		new SubAction(0x110,"b'ThrownFF"),
		new SubAction(0x111,"b'ThrownFB"),
		new SubAction(0x112,"b'ThrownFHi"),	
		new SubAction(0x113,"b'ThrownFLw"),	
		new SubAction(0x114,"b'CaptureCaptain"),	
		new SubAction(0x115,"b'YoshiEgg"),
		new SubAction(0x116,"b'CaptureKoopaHit"),	
		new SubAction(0x117,"b'ThrownKoopaEndF"),	
		new SubAction(0x118,"b'ThrownKoopaEndB"),	
		new SubAction(0x119,"b'CaptureKoopaAirHit"),		
		new SubAction(0x11a,"b'ThrownKoopaAirEndF"),		
		new SubAction(0x11b,"b'ThrownKoopaAirEndB"),		
		new SubAction(0x11c,"b'ThrownKirbyDrinkSShot"),		
		new SubAction(0x11d,"b'ThrownKirbySpitSShot"),	
		new SubAction(0x11e,"b'ShieldBreakFly"),
		new SubAction(0x11f,"b'ShieldBreakFall"),
		new SubAction(0x120,"b'ShieldBreakDownU"),
		new SubAction(0x121,"b'ShieldBreakDownD"),
		new SubAction(0x122,"b'ShieldBreakStandU"),	
		new SubAction(0x123,"b'ShieldBreakStandD"),	
		new SubAction(0x124,"b'ThrownMewtwo"),
		new SubAction(0x125,"b'ThrownMewtwoAir"),

		};
	
	
	public int offset;
	public String name;
	
	public SubAction(int o, String s){
		name=s;
		offset=o;
		
	}
	
	
		//Made in the last version(Pre-crazy hand) to make the names of moves a little prettier in the GUI
		//Currently used for convienience with special move names
		//Can also be used later down the line for supporting multiple languages
		public String getLocalizedName()
		{
			return name.replaceAll("b'", "");
		}
	

}
